---
title: "Notes"
subtitle: 
output:
  html_document:
    highlight: tango
    theme: cosmo
    toc: yes
    toc_depth: 3
    toc_float: yes
---

<!-- ## Section notes -->
Section notes for ECON 402, Intermediate Macroeconomics, with Professor [Chris House](http://www-personal.umich.edu/~chouse/)

## Part I
### 1 A too short introduction
Plotting, two-period budget constraints, comparative statics with the intertemporal budget constraint, agents can always consume their endowment, not being allowed to borrow, indifference curves, derivatives, [optimization](https://umich.box.com/s/t3pnjnvzwyiz861fgoabc5glg91vgw1y)

### 2 Intertemporal choice, the saving supply function, dynamic general equilibrium
Here are the notes for [section 2](https://umich.box.com/s/03fuxxit457y7lfas2ti79u5lobmzzye).
A few take-aways:

+ Intertemporal choice lead to the consumption Euler equation: $\text{MU}(c_1) = (1+r) \text{MU}(c_2)$.
+ The saving supply function: $s_1(r,y) := y_1 - c_1(r,y)$.
We plotted the saving supply function for both 
    * log utility and 
    * linear utility.
+ Dynamic general equilibrium.
Definition 2.2 defines our notion of equilibrium, which is important&mdash;see slide 17 of _Lecture 4\_handouts_.
From national accounting, we saw that $Y = C$ for the endowment economies we explored.
Therefore aggregate saving was $0$.
This equilibrium market-clearing condition provides a procedure for computing equilibrium levels of consumption and the equilibrium interest rate:
    1. Compute the demand functions, $c(r,y)$. Since income is exogenous, these are simply functions of the interest rate.
    2. Using the demand functions, calculate the saving functions.
    3. In equilibrium, the interest rate (price) must adjust so that aggregate saving is $0$. With the interest rate in hand, equilibrium levels of consumption and saving can be read off of items 1. and 2.
    
### 3 Saving supply and saving demand    
Saving supply and saving demand determine the equilibrium [rate of interest](https://umich.box.com/s/e2cb48p3z66ywgh7spcgqpr9zhy12k8y).
Shifters of supply and demand are discussed. 
National accounting requires that $Y_1 = C_1 + I_1$, so $S_1 > 0$.
    
### 4 Summing up
Valuing a job, valuing a job with wage growth, valuing a job with a finite work horizon, PIH with permanent and transitory fluctuations, neoclassical production, [valuing a unit of capitl](https://umich.box.com/s/dlnc24jda0xu9sqifl2uicc4cdmzit4l).
   
## Part II

### 5 Choice under Uncertainty
Precautionary saving in the face of uncertainty, computing expected values, expection, St. Petersburg paradox, concavity and risk aversion, an expanded answer to [problem 5 on Midterm Exam 1](https://umich.box.com/s/ntytbawgba1vpqb2unapnfzls5c3sjzz)

### 6 Introduction to the Solow model of economic growth
Neoclassical production, returns to scale, the final-good-producing firm makes no profits in equilibrium, the Solow model as a dynamic general-equilibrium model,
Solow dynamics with population growth, growth rates of [capital per worker](https://umich.box.com/s/zlyddmutecbi4kapcvjlz1e9tl6l7jl1).

You may also find this slidedeck on the fundamentals of asset pricing [helpful](https://umich.box.com/s/e56gn79e2pkw58h6nb3l40mlp6h99sjw).

### 7 Economic growth continued
The AK model, the AK model with diminishing returns: each new unit of capital added to the economy is slightly less productive than the last&mdash;eventually investment falls to the level of depreciation, the Solow model with population growth and technological change: 
$$
\begin{align*}
g_K = g_Y = g_C = g_I = (1+g_A)(1+n),
\end{align*}$$ 
enter through the narrow gate; for the gate is wide and the road is easy that leads to destruction&mdash;the golden rule: in steady state where $K_{t+1} = K_t = K$,
$$
\begin{align*}
K &= (1-\delta)K + I = (1-\delta)K + Y - C = (1-\delta)K + AK^{\alpha} - C \\
\therefore C &= \delta K + AK^{\alpha} \\
\therefore \frac{\partial C}{\partial K} &= 0 \implies \delta = \text{MPK},
\end{align*}
$$
Solow with human capital from section 12.2 of the House Lecture [notes](https://umich.box.com/s/lf8h7jqhodc0gcyq3gqblbcw2s7wlao0)  

### 8 Midterm Exam II Review
Steady-state $K^{\star}$ with taxes, potential for tax policy to explain cross-country differences in output, wages when $N_t  = 1$, wages after a tax cut, [influx of immigrants](https://umich.box.com/s/4rh0y52xtifhaq1caypp0wr4mlunfxm9)
    
## Selected suggested solutions to homeworks

+ H1.2: A proportional increase to all prices means the implicit price deflator and CPI are the [same](https://umich.box.com/s/zgqslxkgjlxj82p6a086idm592okocv9). The algebra is on the last page.
+ H2: Impatient consumers and the interest rate, the elasticity of intertemporal substitution, and capital taxation and the [user cost](https://umich.box.com/s/gzugioph33wzzt2sydzamvei23roz75q)
+ E1: Extra credit: A cool example of [intertemporal choice](https://umich.box.com/s/k9ogh1w56zarx7rw3itkz4wfdj8n6i9o)

## Answers to questions people have asked

+ The difference between _ex ante_ and _ex post_ interest [rates](https://richryan.github.io/2018/01/22/ex-ante-ex-post.html)
+ Interpreting differences in logs as a [percentage change](https://umich.box.com/s/b55x084x4dg52s0csoqzmj6n8bqin9xe)
+ Are the 10 people who run their own business counted in the establishment survey? [It depends](https://richryan.github.io/2018/02/04/establishment-survey.html).
+ A cool figure that illustrates the effects of [economic growth](https://richryan.github.io/update/2017/08/14/a-gif.html). (By the way, I made that with R Shiny, which is pretty cool.)